### ISSUE TITLE
KNeighborsClassifier predict_proba 'list' object has no attribute 'shape' error with newer scikit-learn-intelex (but not scikit-learn or older scikit-learn-intelex)

### ISSUE THREAD

**Issue by BethanyL** [intel/scikit-learn-intelex#1013]
**Describe the bug**
I fit a KNeighborsClassifier and then used the predict_proba function on a 1x1 example that has not been explicitly converted to a numpy array: neigh.predict_proba([[0.9]]). This is copied from a scikit-learn example and does not produce an error in scikit-learn. It also did not produce an error in a previous version of scikit-learn-intelex. 

**To Reproduce**
1. Install scikit-learn-intelex. I used:
```
python -m venv intelex
source intelex/bin/activate
pip install scikit-learn-intelex
pip install pytest

```
2. Run this example of k-NN classification from [scikit-learn documentation](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html) but after patching scikit-learn:

```
from sklearnex import patch_sklearn
patch_sklearn()

from sklearn.neighbors import KNeighborsClassifier
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)
print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))
```

**Expected behavior**
I expect no errors, since scikit-learn does not produce an error. 

**Output/Screenshots**
Error:
```
Traceback (most recent call last):
  File "knn_standalone.py", line 12, in <module>
    print(neigh.predict_proba([[0.9]]))
  File "/Users/blusch/Documents/intelex/lib/python3.7/site-packages/sklearnex/_device_offload.py", line 182, in wrapper
    result = func(self, *args, **kwargs)
  File "/Users/blusch/Documents/intelex/lib/python3.7/site-packages/sklearnex/neighbors/knn_classification.py", line 244, in predict_proba
    }, X)
  File "/Users/blusch/Documents/intelex/lib/python3.7/site-packages/sklearnex/_device_offload.py", line 159, in dispatch
    return branches[backend](obj, *hostargs, **hostkwargs, queue=q)
  File "/Users/blusch/Documents/intelex/lib/python3.7/site-packages/sklearnex/neighbors/knn_classification.py", line 400, in _onedal_predict_proba
    return self._onedal_estimator.predict_proba(X, queue=queue)
  File "/Users/blusch/Documents/intelex/lib/python3.7/site-packages/onedal/neighbors/neighbors.py", line 476, in predict_proba
    n_queries = _num_samples(X)
  File "/Users/blusch/Documents/intelex/lib/python3.7/site-packages/onedal/datatypes/validation.py", line 334, in _num_samples
    if isinstance(x.shape[0], Integral):
AttributeError: 'list' object has no attribute 'shape'
```

**Environment:**
-  OS: MacOS Monterey 12.4
- Python 3.7.4
- scikit-learn-intelex 2021.6.3
- scikit-learn 1.0.2
- daal4py 2021.6.3
- daal 2021.6.0
- numpy 1.21.6

I have another environment that I created last month using the same steps that does not produce an error on this example. The differences from the above environment are:
- scikit-learn-intelex 2021.5.0
- daal4py 2021.5.0
- daal 2021.5.0

**Comment by PivovarA** [comment]
Hi @BethanyL 
I've created a [PR](https://github.com/intel/scikit-learn-intelex/pull/1014) with a fix

**Comment by Alexsandruss** [comment]
https://github.com/intel/scikit-learn-intelex/pull/1014 is merged and issue is solved.
