### ISSUE TITLE
No device of requested type available

### ISSUE THREAD

**Issue by zhugw** [intel/scikit-learn-intelex#1042]
```
cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

$ nvidia-smi
Fri Sep  9 21:27:01 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    On   | 00000000:02:00.0 Off |                  N/A |
| 39%   37C    P8    10W / 200W |     10MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    On   | 00000000:03:00.0 Off |                  N/A |
| 37%   40C    P8    16W / 250W |     10MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
There are GPU exists, but run example failed
```
>>> from sklearnex import patch_sklearn, config_context
>>> patch_sklearn()
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
>>>
>>> from sklearn.cluster import DBSCAN
>>> import numpy as np
>>> X = np.array([[1., 2.], [2., 2.], [2., 3.], [8., 7.], [8., 8.], [25., 80.]], dtype=np.float32)
>>> with config_context(target_offload="gpu:0"):
...   clustering = DBSCAN(eps=3, min_samples=2).fit(X)
...
WARNING:root:Device support is limited. Please install dpctl for full experience
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/bxt/anaconda3/envs/wenjie/lib/python3.9/site-packages/daal4py/sklearn/_device_offload.py", line 88, in wrapper_with_self
    return wrapper_impl(self, *args, **kwargs)
  File "/home/bxt/anaconda3/envs/wenjie/lib/python3.9/site-packages/daal4py/sklearn/_device_offload.py", line 74, in wrapper_impl
    result = _run_on_device(func, q, obj, *hostargs, **hostkwargs)
  File "/home/bxt/anaconda3/envs/wenjie/lib/python3.9/site-packages/daal4py/sklearn/_device_offload.py", line 62, in _run_on_device
    with sycl_context('gpu' if queue.sycl_device.is_gpu else 'cpu',
  File "/home/bxt/anaconda3/envs/wenjie/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "src/oneapi/oneapi.pyx", line 115, in sycl_context
  File "src/oneapi/oneapi.pyx", line 46, in daal4py._oneapi.sycl_execution_context.__cinit__
RuntimeError: No device of requested type available. Please check https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-dpcpp-system-requirements.html -1 (CL_DEVICE_NOT_FOUND)
>>>

```

**Comment by Alexsandruss** [comment]
Unfortunately, these GPUs are not supported at this moment. You can view supported configurations/system requirements for sklearnex/oneDAL [here](https://intel.github.io/scikit-learn-intelex/system-requirements.html) or [here](https://www.intel.com/content/www/us/en/developer/articles/system-requirements/system-requirements-for-oneapi-data-analytics-library.html).
