### ISSUE TITLE
SyclQueueCreationError: SYCL Device 'gpu:0' could not be created.

### ISSUE THREAD

**Issue by caudjcc** [intel/scikit-learn-intelex#1068]
import numpy as np
import dpctl
from sklearnex import patch_sklearn, config_context
patch_sklearn()
import paddle
from sklearn.cluster import DBSCAN

X = np.array([[1., 2.], [2., 2.], [2., 3.],
            [8., 7.], [8., 8.], [25., 80.]], dtype=np.float32)
with config_context(target_offload="gpu:0"):
    clustering = DBSCAN(eps=3, min_samples=2).fit(X)

**************************************************************
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Temp\ipykernel_7648\2661078756.py", line 11, in <module>
    clustering = DBSCAN(eps=3, min_samples=2).fit(X)

  File "D:\anaconda\env\paddle\lib\site-packages\daal4py\sklearn\_device_offload.py", line 88, in wrapper_with_self
    return wrapper_impl(self, *args, **kwargs)

  File "D:\anaconda\env\paddle\lib\site-packages\daal4py\sklearn\_device_offload.py", line 73, in wrapper_impl
    q, hostargs, hostkwargs = _get_host_inputs(*args, **kwargs)

  File "D:\anaconda\env\paddle\lib\site-packages\daal4py\sklearn\_device_offload.py", line 34, in _get_host_inputs
    q = _get_global_queue()

  File "D:\anaconda\env\paddle\lib\site-packages\sklearnex\_device_offload.py", line 82, in _get_global_queue
    return QueueClass(target)

  File "dpctl\_sycl_queue.pyx", line 335, in dpctl._sycl_queue.SyclQueue.__cinit__

SyclQueueCreationError: SYCL Device 'gpu:0' could not be created.

Could not find a device that matches the specified filter(s)! -1 (CL_DEVICE_NOT_FOUND)
****************************************************************************************
How could i solve it?

**Comment by caudjcc** [comment]
import paddle
print(paddle.device.get_device())
***************************
gpu:0

**Comment by Alexsandruss** [comment]
Hi @caudjcc, could you specify your gpu:0 device name?
I guess it is not one [currently supported by sklearnex](https://intel.github.io/scikit-learn-intelex/system-requirements.html#for-gpu):

> **For GPU**
> Hardware platforms
> - All Intel® integrated and discrete GPUs

**Comment by caudjcc** [comment]
Hi, when i  specify my gpu:0 device name by:

`
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
`
and print by:
`import paddle
print(paddle.device.cuda.get_device_name(0))
print(paddle.device.cuda.device_count())
`
print result:
`
NVIDIA GeForce RTX 3090 Ti
1
`
and then,i run the code:
`with config_context(target_offload="gpu:0"):
    clustering = DBSCAN(eps=3, min_samples=2).fit(X)`
and 
`with config_context(target_offload="0"):
    clustering = DBSCAN(eps=3, min_samples=2).fit(X)`

the result are:
`
  File "dpctl\_sycl_queue.pyx", line 335, in dpctl._sycl_queue.SyclQueue.__cinit__

SyclQueueCreationError: SYCL Device 'gpu:0' could not be created.


Could not find a device that matches the specified filter(s)! -1 (CL_DEVICE_NOT_FOUND)`

and 
`
  File "D:\anaconda\env\paddle\lib\site-packages\daal4py\sklearn\_device_offload.py", line 62, in _run_on_device
    with sycl_context('gpu' if queue.sycl_device.is_gpu else 'cpu',

  File "D:\anaconda\env\paddle\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)

  File "src\oneapi\oneapi.pyx", line 115, in sycl_context

  File "src\oneapi\oneapi.pyx", line 46, in daal4py._oneapi.sycl_execution_context.__cinit__

RuntimeError: No device of requested type available. Please check https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-dpcpp-system-requirements.html -1 (CL_DEVICE_NOT_FOUND)`

**Comment by Alexsandruss** [comment]
This device currently is not supported by scikit-learn-intelex.
