### ISSUE TITLE
Sklearn 1.2 version breaks patch_sklearn()

### ISSUE THREAD

**Issue by BAW2501** [intel/scikit-learn-intelex#1082]
**Describe the bug**
new Sklearn version breaks monkeypatching for patch_sklearn()

**To Reproduce**
1. Setup:  
pip install --upgrade scikit-learn
pip install scikit-learn-intelex

2. Call 
from sklearnex import patch_sklearn
patch_sklearn()
3. Use '....'

**Expected behavior**
Describe what your are expecting from steps above

**Output/Screenshots**
Traceback (most recent call last):
  File "/workspaces/codespaces-jupyter/MLP_CLF.py", line 2, in <module>
    from sklearnex import patch_sklearn
  File "/home/codespace/.python/current/lib/python3.10/site-packages/sklearnex/__init__.py", line 18, in <module>
    from .dispatcher import patch_sklearn
  File "/home/codespace/.python/current/lib/python3.10/site-packages/sklearnex/dispatcher.py", line 22, in <module>
    from daal4py.sklearn._utils import daal_check_version, sklearn_check_version
  File "/home/codespace/.python/current/lib/python3.10/site-packages/daal4py/sklearn/__init__.py", line 17, in <module>
    from .monkeypatch.dispatcher import enable as patch_sklearn
  File "/home/codespace/.python/current/lib/python3.10/site-packages/daal4py/sklearn/monkeypatch/dispatcher.py", line 18, in <module>
    from ..neighbors import KNeighborsRegressor as KNeighborsRegressor_daal4py
  File "/home/codespace/.python/current/lib/python3.10/site-packages/daal4py/sklearn/neighbors/__init__.py", line 18, in <module>
    from ._classification import KNeighborsClassifier
  File "/home/codespace/.python/current/lib/python3.10/site-packages/daal4py/sklearn/neighbors/_classification.py", line 19, in <module>
    from ._base import NeighborsBase, KNeighborsMixin
  File "/home/codespace/.python/current/lib/python3.10/site-packages/daal4py/sklearn/neighbors/_base.py", line 40, in <module>
    from sklearn.neighbors._base import _check_weights
ImportError: cannot import name '_check_weights' from 'sklearn.neighbors._base' (/home/codespace/.python/current/lib/python3.10/site-packages/sklearn/neighbors/_base.py)

**Environment:**
 - OS: Ubuntu 20.04.5 LTS
 - PY 3.10

**Comment by napetrov** [comment]
This is fixed already in code - new deployment to PyPi would happen on next week

**Comment by BAW2501** [comment]
thank you for the swift reply
