### ISSUE TITLE
Unable to build daal4py from source

### ISSUE THREAD

**Issue by rakgb-fujitsu** [intel/scikit-learn-intelex#1219]
I built oneDAL from source (master latest commit) and it generated the necessary lib files and include folders. After I cloned this repository I tried to build daal4py (master latest commit), I'm getting missing files error.

OS: Ubuntu 20.04.6 LTS

Command (ran under **_sudo su_**):
```
$ export DALROOT=/home/ubuntu/sandbox/oneDAL/__release_lnx_gnu/daal/latest
$ export NO_DIST=1
$ python3 setup.py develop --no-deps
```

During the build phase, I get these errors:
```
Disabling support for distributed mode

Generated files are all newer than generator code.Skipping code generation
/usr/lib/python3/dist-packages/setuptools/dist.py:473: UserWarning: Normalizing '20230316.091615' to '20230316.91615'
  warnings.warn(
running develop
Is DPCTL available: False
Project directory is: /home/ubuntu/sandbox/scikit-learn-intelex
Builder directory: /home/ubuntu/sandbox/scikit-learn-intelex/scripts
Install directory: /home/ubuntu/sandbox/scikit-learn-intelex/onedal
Build DPCPP SPMD functionality: False
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- /home/ubuntu/sandbox/scikit-learn-intelex/scripts
-- oneDAL_INCLUDE_DIRS:/home/ubuntu/sandbox/oneDAL/__release_lnx_gnu/daal/latest/include
-- oneDAL_LIBRARY_DIR:/home/ubuntu/sandbox/oneDAL/__release_lnx_gnu/daal/latest/lib/intel64
-- PYTHON_INCLUDE_DIR:/usr/include/python3.8
-- PYTHON_LIBRARY_DIR:/usr/lib
-- NUMPY_INCLUDE_DIRS:/usr/local/lib/python3.8/dist-packages/numpy/core/include
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /usr/local/lib/python3.8/dist-packages/pybind11/include (found version "2.10.3")
-- NUMPY_INCLUDE_DIRS:/usr/local/lib/python3.8/dist-packages/numpy/core/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/sandbox/scikit-learn-intelex/build/backend_host
Scanning dependencies of target _onedal_py_host
[ 21%] Building CXX object CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/common/policy.cpp.o
[ 26%] Building CXX object CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/basic_statistics/basic_statistics.cpp.o
[ 21%] Building CXX object CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/dal.cpp.o
[ 26%] Building CXX object CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/datatypes/data_conversion.cpp.o
[ 36%] Building CXX object CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/datatypes/data_conversion_dpctl.cpp.o
[ 36%] Building CXX object CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/datatypes/table.cpp.o
[ 42%] Building CXX object CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/decomposition/pca.cpp.o
[ 21%] Building CXX object CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/common/spmd_policy.cpp.o
/home/ubuntu/sandbox/scikit-learn-intelex/onedal/basic_statistics/basic_statistics.cpp:17:10: fatal error: oneapi/dal/algo/basic_statistics.hpp: No such file or directory
   17 | #include "oneapi/dal/algo/basic_statistics.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/sandbox/scikit-learn-intelex/onedal/common/policy.cpp:17:10: fatal error: oneapi/dal/detail/policy.hpp: No such file or directory
   17 | #include "oneapi/dal/detail/policy.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
/home/ubuntu/sandbox/scikit-learn-intelex/onedal/decomposition/pca.cpp:16:10: fatal error: oneapi/dal/algo/pca.hpp: No such file or directory
   16 | #include "oneapi/dal/algo/pca.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/ubuntu/sandbox/scikit-learn-intelex/onedal/datatypes/table.cpp:17:10: fatal error: oneapi/dal/table/homogen.hpp: No such file or directory
   17 | #include "oneapi/dal/table/homogen.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/_onedal_py_host.dir/build.make:76: CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/common/policy.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/_onedal_py_host.dir/build.make:141: CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/datatypes/table.cpp.o] Error 1
make[2]: *** [CMakeFiles/_onedal_py_host.dir/build.make:154: CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/decomposition/pca.cpp.o] Error 1
make[2]: *** [CMakeFiles/_onedal_py_host.dir/build.make:63: CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/basic_statistics/basic_statistics.cpp.o] Error 1
/home/ubuntu/sandbox/scikit-learn-intelex/onedal/datatypes/data_conversion.cpp:22:10: fatal error: oneapi/dal/table/homogen.hpp: No such file or directory
   22 | #include "oneapi/dal/table/homogen.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/_onedal_py_host.dir/build.make:115: CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/datatypes/data_conversion.cpp.o] Error 1
In file included from /home/ubuntu/sandbox/scikit-learn-intelex/scripts/../onedal/../onedal/common.hpp:37,
                 from /home/ubuntu/sandbox/scikit-learn-intelex/onedal/dal.cpp:17:
/home/ubuntu/sandbox/scikit-learn-intelex/scripts/../onedal/../onedal/common/dispatch_utils.hpp:21:10: fatal error: oneapi/dal/train.hpp: No such file or directory
   21 | #include "oneapi/dal/train.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/_onedal_py_host.dir/build.make:102: CMakeFiles/_onedal_py_host.dir/home/ubuntu/sandbox/scikit-learn-intelex/onedal/dal.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/_onedal_py_host.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 404, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 383, in run
    custom_build.run(self)
  File "setup.py", line 350, in run
    build_backend.custom_build_cmake_clib(
  File "/home/ubuntu/sandbox/scikit-learn-intelex/scripts/build_backend.py", line 218, in custom_build_cmake_clib
    subprocess.check_call(make_args)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/ubuntu/sandbox/scikit-learn-intelex/build/backend_host', '-j 8']' returned non-zero exit status 2.
```

What am I missing?

**Comment by KulikovNikita** [comment]
@rakgb-fujitsu Can you please share your environment? (`$env > env.log`)

I have not been able to reproduce this failures. I have more or less recent build of oneDAL, conda environment that have no mpi-related packages or dpctl, `NO_DIST` environment variable set to 1.

**Comment by rakgb-fujitsu** [comment]
@KulikovNikita I'm not using conda at all, heres my log:

```
SHELL=/bin/bash
COLORTERM=truecolor
SUDO_GID=1000
SUDO_COMMAND=/usr/bin/su
SUDO_USER=ubuntu
NO_DIST=1
PWD=/home/ubuntu/sandbox/scikit-learn-intelex
LOGNAME=root
HOME=/root
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm-256color
DALROOT=/home/ubuntu/sandbox/oneDAL/__release_lnx_gnu/daal/latest
LESSOPEN=| /usr/bin/lesspipe %s
USER=root
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
SUDO_UID=1000
MAIL=/var/mail/root
_=/usr/bin/env
```

**Comment by napetrov** [comment]
@rakgb-fujitsu could you please also share what oneDAL build command you are using?

**Comment by rakgb-fujitsu** [comment]
@napetrov Built oneDAL using this command:

`make -f makefile daal PLAT=lnx32e COMPILER=gnu`

**Comment by samir-nasibli** [comment]
Hi @rakgb-fujitsu please also provide `export OFF_ONEDAL_IFACE=1`, if you building `daal`

**Comment by napetrov** [comment]
@rakgb-fujitsu  so basically you've compile only daal portion of C++ library but by default daal4py also relay on onedal portion.

alternatively you can build  onedal portion of library as well

**Comment by rakgb-fujitsu** [comment]
@samir-nasibli I'm confused on what this flag does, what is the difference between daal and onedal?

@napetrov sure, will try this.

**Comment by syakov-intel** [comment]
> daal and onedal?

@rakgb-fujitsu Did you overcome your issue with building the library?

**Comment by rakgb-fujitsu** [comment]
@syakov-intel yes, closing this issue.
