### ISSUE TITLE
Cannot install in `Python 3.12` due to `daal4py` not being `py3.12`-ready.

### ISSUE THREAD

**Issue by ayaanhossain** [intel/scikit-learn-intelex#1540]
When trying to install the package on `Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0] on linux` 
```python
$ pip install scikit-learn-intelex
```
everything goes smoothly.

But later
```python
>>> from sklearnex.linear_model import LogisticRegression
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/miniconda3/envs/mlde/lib/python3.12/site-packages/scikit_learn_intelex-2023.2.1-py3.12-linux-x86_64.egg/sklearnex/__init__.py", line 18, in <module>
    from . import utils
  File "/home/ec2-user/miniconda3/envs/mlde/lib/python3.12/site-packages/scikit_learn_intelex-2023.2.1-py3.12-linux-x86_64.egg/sklearnex/utils/__init__.py", line 17, in <module>
    from .validation import _assert_all_finite
  File "/home/ec2-user/miniconda3/envs/mlde/lib/python3.12/site-packages/scikit_learn_intelex-2023.2.1-py3.12-linux-x86_64.egg/sklearnex/utils/validation.py", line 18, in <module>
    from daal4py.sklearn.utils.validation import _assert_all_finite
  File "/home/ec2-user/miniconda3/envs/mlde/lib/python3.12/site-packages/daal4py-2023.2.1-py3.12-linux-x86_64.egg/daal4py/__init__.py", line 38, in <module>
    from daal4py._daal4py import *
ModuleNotFoundError: No module named 'daal4py._daal4py'
```
I run into errors.

Perhaps, I could install `daal4py` via `conda` inside my environment separately, but I never had this issue with when installing `sklearnex` inside my `Python 3.11` environment? I do not recall installing `daal4py` explicitly in that `3.11` environement.

Anyway, I tried this, but apparently `daal4py` is not `Python 3.12`-ready yet.
```python
$ conda install daal4py
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - daal4py -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.11,<3.12.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.12

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.


Note that strict channel priority may have removed packages required for satisfiability.
```

**Comment by napetrov** [comment]
Hi @ayaanhossain 
There are no Python 3.12 builds yet for nether scikit or daal4py. you are actually using 3.11 version of scikit but same doesn't apply to it's dependency daal4py. 

Pypi package for 3.12 will be deployed by late November with next release

as for conda - intel channel will be updated by late november .
Main conda channel - not sure then they are planning to release 
conda-forge channel - i think there are still some dependencies missing for us to be released. 

Support of 3.12 builds are in master - so you can build from sources if needed 
https://github.com/intel/scikit-learn-intelex/pull/1523
