### ISSUE TITLE
RuntimeError: Failed to solve the system of normal equations

### ISSUE THREAD

**Issue by psandev** [intel/scikit-learn-intelex#62]
Hi,
I am running a list of regression models and I am getting the following:
Traceback (most recent call last):
  File "/home/XXXXXX/iowa_housing_functions1.py", line 293, in <module>
    col_num=columns_num, col_cat=columns_cat, data=df_train,run_from_cache=False)
  File "/home/XXXXX/iowa_housing_functions1.py", line 217, in run_regression
    regressor.fit(X_preprocessed_train, y_train)
  File "/home/XXX/miniconda3/envs/idp3/lib/python3.6/site-packages/sklearn/linear_model/ransac.py", line 366, in fit
    base_estimator.fit(X_subset, y_subset)
  File "/home/XXX/miniconda3/envs/idp3/lib/python3.6/site-packages/sklearn/daal4sklearn/linear.py", line 81, in fit
    _daal4py_fit(self, X, y)
  File "/home/XXX/miniconda3/envs/idp3/lib/python3.6/site-packages/sklearn/daal4sklearn/linear.py", line 20, in _daal4py_fit
    lr_res = lr_algorithm.compute(X, y)
  File "build/daal4py_cy.pyx", line 7445, in _daal4py.linear_regression_training.compute
RuntimeError: Failed to solve the system of normal equations

It does not happen when I run it from another virtual environment with non-intel python and sklearn

Thanks a lot.

**Comment by PivovarA** [comment]
Hi @psandev 
This can happen if the matrix is ​​ill-conditioned. Try using L2 regularization or QR decomposition
