### ISSUE TITLE
"import sklearnex" fail on macOS due to daal4py (symbol not found)

### ISSUE THREAD

**Issue by muhlbach** [intel/scikit-learn-intelex#999]
**Describe the bug**
Hi developers! Great work on the extension, I appreciate your hard work!

Now, I'm facing an issue and it might be related to https://github.com/intel/scikit-learn-intelex/issues/152 but I couldn't decode how to fix it. Basically, I can't import sklearnex anymore.

When calling ``import sklearnex``, I get the following error:
```
import sklearnex
Traceback (most recent call last):

  File "/var/folders/lg/d49pbfkx1mxg1y8v5l810v4w0000gn/T/ipykernel_14661/3339319722.py", line 1, in <cell line: 1>
    import sklearnex

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/sklearnex/__init__.py", line 18, in <module>
    from .dispatcher import patch_sklearn

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/sklearnex/dispatcher.py", line 22, in <module>
    from daal4py.sklearn._utils import daal_check_version, sklearn_check_version

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/daal4py/__init__.py", line 30, in <module>
    from daal4py._daal4py import *

ImportError: dlopen(/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/daal4py/_daal4py.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '__ZN3tbb6detail2r110deallocateERNS0_2d117small_object_poolEPvmRKNS2_14execution_dataE'
```
I have tried ``conda clean --all``, ``conda update --all`` and then re-installing ``daal4py``, ``cython``, and ``sklearnex``, but nothing is working.

**Environment:**
 - OS: maxOS Monterey 12.3.1
 - Compiler: Clang 12.0.1 

```
(develop) muhlbach@Muhlbach-MacBook-Pro ~ % conda list
# packages in environment at /Users/muhlbach/opt/anaconda3/envs/develop:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py38hecd8cb5_1  
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
abseil-cpp                20210324.2           he49afe7_0    conda-forge
adjusttext                0.7.3.1                    py_1    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
anyio                     3.5.0            py38h50d1736_0    conda-forge
aom                       3.3.0                h96cf925_1    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
applaunchservices         0.2.1                      py_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38hed1de0f_2    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
arrow-cpp                 7.0.0           py38h2d04a99_4_cpu    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astroid                   2.11.2           py38h50d1736_1    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
autocrosswalk             0.0.24                    dev_0    <develop>
autograd                  1.3                        py_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
aws-c-cal                 0.5.11               hd2e2f4b_0    conda-forge
aws-c-common              0.6.2                h0d85af4_0    conda-forge
aws-c-event-stream        0.2.7               hb9330a7_13    conda-forge
aws-c-io                  0.10.5               h35aa462_0    conda-forge
aws-checksums             0.1.11               h0010a65_7    conda-forge
aws-sdk-cpp               1.8.186              h766a74d_3    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       pyhd8ed1ab_1003    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     22.3.0             pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl    conda-forge
blas-devel                3.9.0              12_osx64_mkl    conda-forge
bleach                    5.0.0              pyhd8ed1ab_0    conda-forge
bodyguard                 0.0.72                    dev_0    <develop>
bottleneck                1.3.4            py38h4277f33_1    conda-forge
brotli                    1.0.9                h5eb16cf_7    conda-forge
brotli-bin                1.0.9                h5eb16cf_7    conda-forge
brotlipy                  0.7.0           py38hed1de0f_1004    conda-forge
build                     0.7.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
causallib                 0.8.1                    pypi_0    pypi
certifi                   2021.10.8        py38h50d1736_2    conda-forge
cffi                      1.15.0           py38h1a44b6c_0    conda-forge
chardet                   4.0.0            py38h50d1736_3    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.2            py38h50d1736_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
cmarkgfm                  0.8.0            py38hed1de0f_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
conda-content-trust       0.1.3              pyhd8ed1ab_0    conda-forge
conda-package-handling    1.8.1            py38hed1de0f_1    conda-forge
conda-repo-cli            1.0.4              pyhd3eb1b0_0  
conda-verify              3.1.1           py38h50d1736_1004    conda-forge
cookiecutter              1.7.3              pyh6c4a22f_1    conda-forge
cramjam                   2.5.0            py38h74accb0_0    conda-forge
cryptography              36.0.2           py38h826b3c8_1    conda-forge
cvxopt                    1.3.0            py38h102f16f_1    conda-forge
cvxpy                     1.2.0            py38h50d1736_0    conda-forge
cvxpy-base                1.2.0            py38h52e9a12_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.28          py38h038c8f4_2    conda-forge
daal                      2021.5.0           h694c41f_782    conda-forge
daal4py                   2021.5.0         py38h39ff551_0    conda-forge
dal                       2021.5.0           h694c41f_782    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbus                      1.13.6               h811a1a6_3    conda-forge
dcor                      0.5.3              pyhd8ed1ab_0    conda-forge
debugpy                   1.6.0            py38h038c8f4_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
deprecated                1.2.13             pyh6c4a22f_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
docutils                  0.16             py38h50d1736_3    conda-forge
dsdp                      5.8               h6e329d1_1203    conda-forge
econnlp                   0.0.7                     dev_0    <develop>
ecos                      2.0.10           py38hbe852b5_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.4.8                h96cf925_0    conda-forge
fastparquet               0.8.0            py38hbe852b5_1    conda-forge
ffmpeg                    4.4.1                h2579ba5_2    conda-forge
fftw                      3.3.10          nompi_hf082fe4_102    conda-forge
filelock                  3.6.0              pyhd8ed1ab_0    conda-forge
flake8                    4.0.1              pyhd8ed1ab_2    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.32.0           py38hed1de0f_0    conda-forge
formulaic                 0.3.3              pyhd8ed1ab_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fsspec                    2022.3.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38h50d1736_5    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
gflags                    2.2.2             hb1e8313_1004    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.70.2               hcf210ce_4    conda-forge
glib-tools                2.70.2               hcf210ce_4    conda-forge
glob2                     0.7                        py_0    conda-forge
glog                      0.6.0                h8ac2a54_0    conda-forge
glpk                      4.65              h0f52abe_1004    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
gnutls                    3.6.13               h756fd2b_1    conda-forge
grpc-cpp                  1.43.2               hb6405b5_1    conda-forge
gsl                       2.7                  h93259b0_0    conda-forge
huggingface_hub           0.5.1              pyhd8ed1ab_0    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py38h50d1736_1    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_1    conda-forge
importlib_resources       5.7.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
interface_meta            1.3.0              pyhd8ed1ab_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.13.0           py38h60dac5d_0    conda-forge
ipython                   7.32.0           py38h50d1736_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.0              pyhd8ed1ab_0    conda-forge
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.1           py38h50d1736_1    conda-forge
jellyfish                 0.9.0            py38hed1de0f_1    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0d85af4_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.2.2              pyhd8ed1ab_1    conda-forge
jupyter_core              4.9.2            py38h50d1736_0    conda-forge
jupyter_server            1.16.0             pyhd8ed1ab_1    conda-forge
jupyterlab                3.3.3              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.12.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.0              pyhd8ed1ab_0    conda-forge
keyring                   23.4.0           py38h50d1736_2    conda-forge
kiwisolver                1.4.2            py38h8b7791e_1    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lame                      3.100             h35c211d_1001    conda-forge
lazy-object-proxy         1.7.1            py38hed1de0f_1    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libarchive                3.5.2                h2b60450_1    conda-forge
libblas                   3.9.0              12_osx64_mkl    conda-forge
libbrotlicommon           1.0.9                h5eb16cf_7    conda-forge
libbrotlidec              1.0.9                h5eb16cf_7    conda-forge
libbrotlienc              1.0.9                h5eb16cf_7    conda-forge
libcblas                  3.9.0              12_osx64_mkl    conda-forge
libclang                  13.0.1          default_he082bbe_0    conda-forge
libcrc32c                 1.1.2                he49afe7_0    conda-forge
libcurl                   7.82.0               h9f20792_0    conda-forge
libcxx                    13.0.1               hc203e6f_0    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libevent                  2.1.10               h815e4d9_4    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_4    conda-forge
libgoogle-cloud           1.35.0               h52a585b_2    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0              12_osx64_mkl    conda-forge
liblapacke                3.9.0              12_osx64_mkl    conda-forge
liblief                   0.11.5               he49afe7_1    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libllvm11                 11.1.0               hd011deb_3    conda-forge
libllvm13                 13.0.1               h64f94b2_2    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     14.2                 hea3049e_0    conda-forge
libprotobuf               3.19.4               hcf210ce_0    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libspatialindex           1.9.3                he49afe7_4    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libthrift                 0.16.0               h9702cd6_1    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libutf8proc               2.7.0                h0d85af4_0    conda-forge
libvpx                    1.11.0               he49afe7_3    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxgboost                1.5.1            cpu_h598c753_2    conda-forge
libxml2                   2.9.12               h7e28ab6_1    conda-forge
libxslt                   1.1.33               h1acebb3_3    conda-forge
libzlib                   1.2.11            h6c3fc93_1014    conda-forge
lightgbm                  3.3.2            py38hffa2396_0    conda-forge
linearmodels              4.26             py38h4277f33_0    conda-forge
llvm-openmp               13.0.1               hcb1a161_1    conda-forge
llvmlite                  0.38.0           py38hbfc0824_1    conda-forge
lxml                      4.8.0            py38hed1de0f_2    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
lzo                       2.10              haf1e3a3_1000    conda-forge
markupsafe                2.1.1            py38hed1de0f_1    conda-forge
matplotlib-base           3.5.1            py38hc7d2367_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
metis                     5.1.0             h2e338ed_1006    conda-forge
miceforest                5.1.2              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38h96a0964_1005    conda-forge
mizani                    0.7.4              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h89fa619_689    conda-forge
mkl-devel                 2021.4.0           h694c41f_690    conda-forge
mkl-include               2021.4.0           hf224eb6_689    conda-forge
mkl-service               2.4.0            py38haa1d401_0    conda-forge
mkl_fft                   1.3.1            py38h0834169_1    conda-forge
mkl_random                1.2.2            py38h1f261ad_0    conda-forge
mlregression              0.1.10                    dev_0    <develop>
mpfr                      4.1.0                h0f52abe_1    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     4.0.2              hd33e60e_100    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           0.4.3            py38h50d1736_5    conda-forge
mysql-common              8.0.28               hab7e275_3    conda-forge
mysql-libs                8.0.28               h2a44bf5_3    conda-forge
navigator-updater         0.2.1                    py38_1  
nbclassic                 0.3.7              pyhd8ed1ab_0    conda-forge
nbclient                  0.6.0              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.3.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
nettle                    3.6                  hedd7734_0    conda-forge
networkx                  2.8                pyhd8ed1ab_0    conda-forge
ninja                     1.10.2               h940c156_1    conda-forge
nltk                      3.6.7              pyhd8ed1ab_0    conda-forge
notebook                  6.4.10             pyha770c72_0    conda-forge
notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
nspr                      4.32                 hcd9eead_1    conda-forge
nss                       3.77                 hfce436b_0    conda-forge
numba                     0.55.1           py38h41dd760_0    conda-forge
numexpr                   2.8.0            py38hb872667_2    conda-forge
numpy                     1.21.5           py38h2e5f0a9_1  
numpy-base                1.21.5           py38h3b1a694_1  
numpydoc                  1.2.1              pyhd8ed1ab_0    conda-forge
occ2vec                   0.0.20                    dev_0    <develop>
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openblas                  0.3.20          openmp_h5ad848b_0    conda-forge
openh264                  2.1.1                hfd3ada9_0    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1n               h6c3fc93_0    conda-forge
orc                       1.7.3                h84518c8_0    conda-forge
osqp                      0.6.2.post0      py38ha53d530_3    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
palettable                3.3.0                      py_0    conda-forge
pandas                    1.4.2            py38hb872667_1    conda-forge
pandoc                    2.18                 h694c41f_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pep517                    0.12.0           py38h50d1736_2    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.0            py38h7207f37_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.2              pyhd8ed1ab_0    conda-forge
platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
plotly                    5.7.0              pyhd8ed1ab_0    conda-forge
plotnine                  0.8.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py38h50d1736_3    conda-forge
poyo                      0.5.0                      py_0    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.29             pyha770c72_0    conda-forge
property-cached           1.6.4                      py_0    conda-forge
property_cached           1.6.4                         0    conda-forge
psutil                    5.9.0            py38hed1de0f_1    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-lief                   0.11.5           py38ha048514_1    conda-forge
py-xgboost                1.5.1           cpu_py38he866dac_2    conda-forge
pyaml                     21.10.1            pyhd8ed1ab_0    conda-forge
pyarrow                   7.0.0           py38h0bc1b44_4_cpu    conda-forge
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py38hed1de0f_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.4.0              pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyhdfe                    0.1.0              pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pylint                    2.13.5             pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynndescent               0.5.6              pyh6c4a22f_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38h50d1736_8    conda-forge
pyqt-impl                 5.12.3           py38hb240fba_8    conda-forge
pyqt5-sip                 4.19.18          py38h1d3b384_8    conda-forge
pyqtchart                 5.12             py38hb240fba_8    conda-forge
pyqtwebengine             5.12.1           py38hb240fba_8    conda-forge
pyreadstat                1.1.4            py38h4fe204b_0    conda-forge
pyrsistent                0.18.1           py38hed1de0f_1    conda-forge
pysocks                   1.7.1            py38h50d1736_5    conda-forge
python                    3.8.13          h394c593_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python-libarchive-c       4.0              py38h50d1736_1    conda-forge
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.4.1              pyhd8ed1ab_1    conda-forge
python-slugify            6.1.1              pyhd8ed1ab_0    conda-forge
python.app                1.4              py38h96a0964_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.10.0          cpu_py38hfbc0695_1    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38hed1de0f_4    conda-forge
pyzmq                     22.3.0           py38h8647ca9_2    conda-forge
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qdldl-python              0.1.5            py38ha53d530_2    conda-forge
qstylizer                 0.2.1              pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h2a607e2_5    conda-forge
qtawesome                 1.1.1              pyhd8ed1ab_0    conda-forge
qtconsole                 5.3.0              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.0              pyhd8ed1ab_0    conda-forge
qtpy                      2.0.1              pyhd8ed1ab_0    conda-forge
re2                       2022.02.01           he49afe7_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
readme_renderer           34.0               pyhd8ed1ab_0    conda-forge
regex                     2022.3.15        py38hed1de0f_1    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
rfc3986                   2.0.0              pyhd8ed1ab_0    conda-forge
rich                      12.2.0             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               hbbacdb1_2    conda-forge
rope                      1.0.0              pyhd8ed1ab_0    conda-forge
rtree                     1.0.0            py38hc59ffc2_1    conda-forge
ruamel_yaml               0.15.80         py38h96a0964_1006    conda-forge
sacremoses                0.0.49             pyhd8ed1ab_0    conda-forge
scikit-learn              1.0.2            py38h37f3bb3_0    conda-forge
scikit-learn-intelex      2021.5.0         py38h50d1736_1    conda-forge
scikit-lego               0.6.10             pyhd8ed1ab_0    conda-forge
scikit-misc               0.1.4            py38h4fa9f20_3    conda-forge
scikit-optimize           0.9.0              pyhd8ed1ab_1    conda-forge
scipy                     1.8.0            py38hd329d04_1    conda-forge
scs                       3.2.0            py38hb730a05_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
sentence-transformers     2.2.0              pyhd8ed1ab_0    conda-forge
sentencepiece             0.1.96           py38h8b7791e_1    conda-forge
setuptools                62.1.0           py38h50d1736_0    conda-forge
setuptools-scm            6.4.2              pyhd8ed1ab_0    conda-forge
sip                       6.5.1            py38ha048514_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h6db0672_2    conda-forge
snappy                    1.1.8                hb1e8313_3    conda-forge
sniffio                   1.2.0            py38h50d1736_3    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sphinx                    4.5.0              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.3.0            py38h50d1736_0    conda-forge
spyder-kernels            2.3.0            py38h50d1736_0    conda-forge
sqlite                    3.38.2               hb516253_0    conda-forge
statsmodels               0.13.2           py38hbe852b5_0    conda-forge
suitesparse               5.10.1               h7aff33d_1    conda-forge
svt-av1                   0.9.1                h96cf925_0    conda-forge
tbb                       2021.5.0             hbb4e6a2_1    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
terminado                 0.13.3           py38h50d1736_1    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.2.2              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss                   0.4             pyhd8ed1ab_1002    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tokenizers                0.10.3           py38h7d8d1bc_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
torchvision               0.12.0          cpu_py38h1d2bf09_1    conda-forge
tornado                   6.1              py38hed1de0f_3    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
transformers              4.16.2             pyhd8ed1ab_0    conda-forge
twine                     4.0.0              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.2            py38h96a0964_0    conda-forge
typing-extensions         4.1.1                hd8ed1ab_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
ujson                     5.2.0            py38h038c8f4_1    conda-forge
umap-learn                0.5.3            py38h50d1736_0    conda-forge
unicodedata2              14.0.0           py38hed1de0f_1    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
watchdog                  2.1.7            py38h42c56ba_1    conda-forge
waterfallcharts           3.8                      pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.3.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
widgetsnbextension        3.6.0            py38h50d1736_0    conda-forge
wrapt                     1.14.0           py38hed1de0f_1    conda-forge
wurlitzer                 3.0.2              pyhd8ed1ab_2    conda-forge
x264                      1!161.3030           h0d85af4_1    conda-forge
x265                      3.5                  hbb4e6a2_3    conda-forge
xgboost                   1.5.1           cpu_py38h39ba569_2    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.0.3              pyhd8ed1ab_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h6c3fc93_1014    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
```

**Comment by PivovarA** [comment]
Hi @muhlbach
Thanks for the compliment 😊.
And thanks for pointing out the problem.
This is unexpected behavior. 
I just checked the installation and importing of sklearnex on my macos machine and it looks like everything works fine. 
So I would like to clarify: how do you install sklearnex?
There is no need to install daal4py and intel extension for sklearn separately, all the necessary packages will download automatically.
If you are installing sklearnex using anaconda, the appropriate command would be:
`conda install scikit-learn-intelex`
In addition, perhaps installing via pip will solve the problem:
`python -m pip install scikit-learn-intelex`

**Comment by muhlbach** [comment]
@PivovarA 
Of course, you deserve the compliments, I love this extension and it is really speeding up my research!

I guess I installed a package recently that messed up the installation. I'm trying to go back through revisions right now, but can't seem to find one working. I'm always installing ``sklearnex`` via conda. Would you recommend me to uninstall ``daal4py`` and ``cython`` and then try again?

**Comment by PivovarA** [comment]
@muhlbach 
Yes, it looks like something went wrong during the installation process. 
To verify this, you can create a new environment in conda and try to install and import `sklearnex` there by command I mention before. 
If this will work, then you can try to remove `daal4py` and `cython` in the main environment and try to install `sklearnex` again.

**Comment by muhlbach** [comment]
@PivovarA 
Okay, thanks. I have a feeling that ``cython`` is behind the trouble because I recently installed a package that installed ``cython`` under the hood. Does ``sklearnex`` install and/or uses ``cython``?

I will btw remove both ``cython`` and ``daal4py`` and see if that works. Keep you posted.

**Comment by muhlbach** [comment]
Update: It does not help uninstalling ``daal4py`` and re-installing ``sklearnex``.

**Comment by PivovarA** [comment]
Hi @muhlbach 
As far as I know, we don't have runtime dependencies on `cython`, so it shouldn't affect it. 
I would recommend separately reinstalling all Intel libraries: `tbb`, `daal`, `dal`, `daal4py`, as they have binary dependencies. 
In addition, it would be a great help to us if you could clarify whether it worked for you to install `sklearnex` in the new environment, so that it will be clear for us that the problem is not in the system.

**Comment by muhlbach** [comment]
Works on a clean installation!
